### ISSUE TITLE
AV & recording for lightning talks, recaps

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#10]
We wish to record the lightning talks & unconference recaps to allow others to learn even if they're not able to attend.

- [x] What are the AV capabilities of the HSPH venue?
- [x] What are the recording capabilities of the HSPH venue?
- [x] If the venue has none of the above, how do we proceed?

**Comment by raynamharris** [comment]
- Do we have the ability to live stream for remote participation?
- If no live stream, can we set up a WebEx (or something similar, but webex was used at the last f2f)?

**Comment by raynamharris** [comment]
@marypiper, so you know anything about AV at the venue?

**Comment by ctb** [comment]
we have a traveling google hangout -> youtube chromebox system that is
straightforward to set up.

**Comment by vmbrasseur** [comment]
Which will be helpful, but generally knowing about the in-room AV is also needed.

**Comment by marypiper** [comment]
Sorry for the delay - I was off yesterday. This specific room I will check with our contact at Countway library, but all of the other rooms we teach in at Countway library have the following:

AV - Conference Phone (Built Into Rm.)
AV - PowerPoint-Friendly
AV - TelePresence (Cisco Standard Technology)
AV - Webex (two-way collaboration and recording)
AV - Wireless Laptop Sharing (Cisco Proximity)

I assume the Lahey Room does as well, but I will double-check just to make sure.

**Comment by vmbrasseur** [comment]
I've downloaded the Day 1 show-and-tell videos to my Dropbox:

https://www.dropbox.com/sh/hwu24o6j165a0eq/AADKbD-5zKZBnJ4NAZsGD0fda?dl=0

The original plan was to upload these to Internet Archive. We need to sort that out, since they can't stay in my Dropbox long term.

**Comment by vmbrasseur** [comment]
That comment should've gone in #13. Oops. Please reply over there.

**Comment by raynamharris** [comment]
All May workshop videos were posted on the Internet archive in 2 playlists (one for each day). They can be viewed here: https://archive.org/details/nih-dcppc
