### ISSUE TITLE
Childcare

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#11]
We would like to provide childcare for the event.

**Comment by vmbrasseur** [comment]
In last week's call we said it's unlikely that we'll be able to arrange for childcare for this month's event since we have such a short lead time.

Confirm that HSPH can't provide it and if not, close this issue.

**Comment by vmbrasseur** [comment]
![screen shot 2018-05-14 at 10 03 14](https://user-images.githubusercontent.com/298927/40011921-0dde32ba-575e-11e8-832e-0f65138b960b.png)

Here are the answers to the childcare question at registration, as of today. So we do have a few people who will need childcare assistance.

@raynamharris Just to confirm, we don't have specific plans for covering this yet, yes? I want to verify that before asking our HSPH friends for help. :)

**Comment by raynamharris** [comment]
@vmbrasseur we don't have specific plans but @swzCuroverse has expressed an interest in helping up accommodate those who need to bring a travel companion.

**Comment by vmbrasseur** [comment]
NIH grants don't allow for us to reimburse attendees for childcare, so that's not directly an option.

We're going to reach out to the 2.5 people to see what their needs are.

**Comment by raynamharris** [comment]
Current status with registration as of mid-day 
- 1 maybe/ unsure
- 1 yes

**Comment by raynamharris** [comment]
okay, so all the attendees have taken care of their childcare needs on their own. 

We can close this issues a soon as we cap registration.

**Comment by vmbrasseur** [comment]
Since we don't need to worry about this, just closing the issue.
