### ISSUE TITLE
Storage of workshop videos

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#13]
Hopefully (AV gods willing), we'll be recording lightning talks & unconference recaps for each of the workshops.

Where do we put all of these media files so they can be accessed & shared easily?

**Comment by vmbrasseur** [comment]
Via email I suggested Internet Archive for this. Titus +1'd.

Today I wrote my friends at the Archive to get us a collection to contain all of our files under a single, easy to find & share, URL. They can be reticent to hand out collections sometimes, but I think this one won't be a problem.

**Comment by vmbrasseur** [comment]
Because this needs to be done before the May event, I'll drop it into that project.

**Comment by vmbrasseur** [comment]
If you would like to be an admin of this collection, please send me your Internet Archive username (the email address you use to log in).

**Comment by vmbrasseur** [comment]
I've received info from Rayna but no one else yet. I've just emailed pinging folks to see whether anyone else wants access.

I'll be making the request on Friday.

**Comment by vmbrasseur** [comment]
I've downloaded the Day 1 show-and-tell videos to my Dropbox:

https://www.dropbox.com/sh/hwu24o6j165a0eq/AADKbD-5zKZBnJ4NAZsGD0fda?dl=0

The original plan was to upload these to Internet Archive. We need to sort that out, since they can't stay in my Dropbox long term.

**Comment by ctb** [comment]
On Thu, May 31, 2018 at 02:59:56PM +0000, VM Brasseur wrote:
> I've downloaded the Day 1 show-and-tell videos to my Dropbox:
> 
> https://www.dropbox.com/sh/hwu24o6j165a0eq/AADKbD-5zKZBnJ4NAZsGD0fda?dl=0
> 
> The original plan was to upload these to Internet Archive. We need to sort that out, since they can't stay in my Dropbox long term.

There is still discussion about what should be public vs what should be
private. I suggest asking the video presenters what can be made public.

**Comment by vmbrasseur** [comment]
It may be better to say, "We'll be posting these publicly. Speak now if you'd like us not to post your video." We're more likely to get folks allowing open/public distribution.

**Comment by ctb** [comment]
+1

"we are going to post these by XXX. Please let us know by then if you want
to keep your video private."

**Comment by vmbrasseur** [comment]
See also: https://github.com/dcppc/dcppc-workshops/issues/19#issuecomment-393572828

**Comment by vmbrasseur** [comment]
Probably best to wait for the Day 2 videos to be ready to upload. Then we can send a single email including all presenters.

@raynamharris, could you drop links to the videos into the team channel or something whenever you come up for air post-workshop?

**Comment by raynamharris** [comment]
day 2 videos dropped into the channel here https://nih-dcppc.slack.com/archives/C7ULH1XRT/p1527893814000342

**Comment by vmbrasseur** [comment]
Downloaded, thanks! They're at the same dropbox link as above.

I just emailed w/more information about the communication/upload plan.

**Comment by raynamharris** [comment]
Workshop videos (in playlist format) are here

https://archive.org/details/commonspilot-may2018workshop-day01

https://archive.org/details/commonspilot-may2018workshop-day02

**Comment by raynamharris** [comment]
All NIH-DCPPC related videos can be added to this collection https://archive.org/details/nih-dcppc
