### ISSUE TITLE
Confirm catering

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#14]
- [x] We need to confirm with HSPH whether they can help with catering for the event.
- [x] confirm headcount - currently 55 
- [x] determine catering budget
- [x] incorporate diet information (see below)

**Comment by marypiper** [comment]
This is Mary from HSPH, and we can help with catering. Do you know how many people we should be ordering breaks/lunch for?

**Comment by vmbrasseur** [comment]
@marypiper We've capped attendance at 50 for this one to make sure the group will fit in the rooms.

As of today, Ti.to is showing that we have 33 registrations so far.

**Comment by vmbrasseur** [comment]
And here's the information we have so far about dietary restrictions:

![screen shot 2018-05-13 at 14 40 03](https://user-images.githubusercontent.com/298927/39972033-9b944d36-56bb-11e8-9f99-532db30b164f.png)

**Comment by vmbrasseur** [comment]
@raynamharris met with @marypiper today. Information in the [Workshop Planning agenda document](https://docs.google.com/document/d/1oW0qklVGNC7BWlE62wodwqefOEyt1r9_mENFFXDySso/edit#heading=h.mf1hyqa004v1).
