### ISSUE TITLE
Can we use the childcare at BOSC? Yes!

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#15]
They have childcare…can we coattail on it?

**Comment by raynamharris** [comment]
Here's the BOSC page about childcare
https://galaxyproject.org/events/gccbosc2018/childcare/

form for childcare request: https://docs.google.com/forms/d/e/1FAIpQLSd0hcy41htUaXJi4Pcjcqlhpvws0YV_aoT0j1VXuq0kY9bwlw/viewform?c=0&w=1
form for nursing room request: https://docs.google.com/forms/d/e/1FAIpQLSfBj9iscgZaX5iC5UG3yoZjZMWvsE3pe98qRe4gbn44S_UXjw/viewform

**Comment by vmbrasseur** [comment]
Yeah, but will they mind if we tell our attendees it's OK to use their childcare? We should verify rather than assume.

I think Brad may be able to give us some information about this.

**Comment by raynamharris** [comment]
Okay, will confirm with Brad.

**Comment by raynamharris** [comment]
- The BOSC choices are a la carte so whatever people prefer if fine. 
- No need to go to BOSC or training (although we'd love to have folks there). 
- Childcare isn't dependent on attendance or anything else, we're only setting it up to make it easier for parents.
