### ISSUE TITLE
Accessibility of the venue?

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#16]
What do we know about the accessibility of the venue? I assume it's good, since it's HSPH, but we need to confirm that assumption.

**Comment by vmbrasseur** [comment]
@marypiper Do you have information about this one? I didn't see any information on the HSPH website, but I may have overlooked it.

**Comment by raynamharris** [comment]
Re accessibility (see https://www.countway.harvard.edu/about/directions):

Nearby parking:
- Metered street parking on Huntington Avenue
- Brigham and Women's parking garage on Francis Street
- Children's Hospital parking garage on Longwood Avenue

**Wheelchair Accessibility:** The path to Countway from Huntington Ave. and Brigham Circle is sunken below street level. Wheelchair access between the two locations requires the use of two outdoor elevators.
- One is on Huntington Ave. near the steps descending from street level to Countway. 
- The other is at the Countway entrance. 
Each elevator has a call box if you need help. You may also call (617) 432-1379.

Service animals are welcome at Countway.

Related: we have these 5 rooms reserved: 
- Lahey Room -- flexible rectangle desk arrangements for 50 people
- Room 423 -- flexible desk arrangements for 15-20 people
- Room 320 -- flexible desk arrangements for 15-20 people
- Ballard -- larger room
- Room 403 -- larger room

![](https://modlearning.files.wordpress.com/2012/09/2012-09-14-10-40-50.jpg)

**Comment by vmbrasseur** [comment]
I added accessibility info to the workshop readme: https://github.com/dcppc/2018-may-workshop/pull/5
