### ISSUE TITLE
Post-mortem

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#19]
After the event is done, collect information on how it went (both from our and the attendees' perspectives) as well as ideas on how to improve the process in the future.

Related to #7 .

**Comment by vmbrasseur** [comment]
For June, make sure we get approval in advance not only to record but also to post the videos publicly.

**Comment by vmbrasseur** [comment]
@karenword How can folks access the assessment results?

**Comment by karenword** [comment]
I will create two reports to share at our next meeting -- one with counts & summaries that can be shared publicly, and one with (potentially identifying) free-response text. We can talk about what to do with these then.

**Comment by raynamharris** [comment]
Formal assessment for the May workshop was posted here https://github.com/dcppc/internal/pull/28
