### ISSUE TITLE
Preserving/presenting notes from workshop unconferences

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#2]
We expect a lot of good collaboration during the unconferences themselves, but we need to provide a way to preserve and share that information so others can benefit.

**Comment by vmbrasseur** [comment]
The answer to this question will apply to all of the workshops, but since we have to have that resolved before the first one in May I'll drop this into the May project.

**Comment by vmbrasseur** [comment]
Will be in May DCPPC google drive folder

**Comment by raynamharris** [comment]
All notes from breakout groups are in google drive under DCPPC coordination folder > 2018 May workshop > breakout group notes

Notes from the hackathon planning meetings are in the 2018 May workshop folder, but I will be moving those to github for easier reference
