### ISSUE TITLE
confirm dates for 2018 workshops

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#23]
- [x] Boston - May 30 - 31 (with help from Brad Chapman)
- [x] Portland - June 29 - 30 (Reed College, associated with BOSC)
- [x] UNC -  July 25-26 (with help from Sarah Davis)
- [x] Chicago - August 27-28 (with help from Ian Foster, Heather, Rick) 
- [x] Boston - Sept 20-21 Boston (with help from Mercè Crosas)
- [x]  NIH -  October 15-16  (concurrent with NIH meeting on 16)

**Comment by ctb** [comment]
let's advertise the Portland dates ASAP!

**Comment by raynamharris** [comment]
When should we (and who should) reach out to Stan, Ian, and KC2 (perhaps Mercè) about picking dates for these workshops? cc @ctb @awz

**Comment by ctb** [comment]
as soon as possible! Stan and Karen for NC, Ian for Chicago, and then let's set tentative dates with either Merce or the Broad or Seven Bridges, whatever @swzCuroverse  recommends.

**Comment by raynamharris** [comment]
(from email with Sarah and Sasha)

Stan recommends
- Thursday/Friday, July 26-27 

​Stan could also do
- July 25-26 (Wednesday/Thursday)
- July 27-28 (Friday/Saturday)
- July 31-Aug 1 (Tuesday/Wednesday) 

Who wants to check to see if this works for Viven? @ctb? @awz? me?

**Comment by raynamharris** [comment]
See also #53  for july dates

**Comment by raynamharris** [comment]
See also #54 for September dates

**Comment by raynamharris** [comment]
Dates for July finalized! July 25-26!

**Comment by raynamharris** [comment]
Remaining 4 workshops annunced last week (see https://github.com/dcppc/dcppc-workshops/pull/81) 
* July 25-26 in Chapel Hill, NC: [workshop website](http://nih-data-commons.us/2018-july-workshop/), [GitHub repository](https://github.com/dcppc/2018-july-workshop) 
 * August 27-28 in Chicago, IL: [workshop website](http://nih-data-commons.us/2018-august-workshop/), [GitHub repository](https://github.com/dcppc/2018-august-workshop)  
 * September 20-21 in Boston, MA: [workshop website](http://nih-data-commons.us/2018-september-workshop/), [GitHub repository](https://github.com/dcppc/2018-september-workshop)
 * October 15-16 in Bethesda, MD: _stay tuned for details!_
