### ISSUE TITLE
Broadcast end of June dates ASAP.

### ISSUE THREAD

**Issue by ctb** [dcppc/dcppc-workshops#25]
we should get this on people's calendars sooner rather than later!

**Comment by raynamharris** [comment]
Dates confirmed Friday-Saturday, June 29-30
working on invite email now

**Comment by ctb** [comment]
Agree re crossed wires! Dave the date sounds good. So does save the date :)

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by raynamharris** [comment]
Draft email created. 

Will send to leads, data stewards, project contacts, and vivien next

**Comment by raynamharris** [comment]
done
