### ISSUE TITLE
Map/Directions and Suggested Eating Places for Attendants (nice to have)

### ISSUE THREAD

**Issue by swzCuroverse** [dcppc/dcppc-workshops#27]

**Comment by vmbrasseur** [comment]
Once we have these, we should add them to the workshop information repo:

https://github.com/dcppc/2018-may-workshop/

**Comment by vmbrasseur** [comment]
@swzCuroverse @awz Could one of you tap a local to whip up a list of recommended eateries?

**Comment by raynamharris** [comment]
Can we make some reservations at restaurants in addition to suggesting places to go? This could help foster some spontaneous networking, especially if anyone is traveling alone or doesn't know many people yet.

**Comment by vmbrasseur** [comment]
Sasha's going to ask Brad & Mary for help with this.

**Comment by vmbrasseur** [comment]
I'm assuming Rayna has this on intro slides now, since it's Thursday, so I'll close this issue.
