### ISSUE TITLE
Include accommodations link in the invite

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#29]
We received this email after the May workshop invite went out:

> Do you have advice about the schedule (i.e., when do you expect sessions to begin on the 30th and end on the 31st?) or accommodations (i.e., is there a set of recommended hotels or should we fend for ourselves? If the latter, are reimbursements subject to the GSA per diem rates?). 
> 
>  Sorry if this has been covered elsewhere. 

We should make sure the June (and other) announcement includes a link to accommodations in the area.

**Comment by raynamharris** [comment]
this was included in the announce the date #28
