### ISSUE TITLE
Short URLs

### ISSUE THREAD

**Issue by charlesreid1** [dcppc/dcppc-workshops#34]
I noticed a few very long links in the readme (airbnb and google maps). If you have a really long link, you can use a link shortening service to make them a bit easier to deal with. I like tinyurl.com because it's simple and you can pick custom URLs like tinyurl.com/my-cool-workshop-name. You can also get a bit.ly account and create short URLs linked to your account, and collect analytics on how many people click your short URL. Google also has a URL shortener at goo.gl.

**Comment by raynamharris** [comment]
Ah yes, I really like the Google URL shortener. It def makes sense for airbnb and google maps. Do also recommend for long GitHub paths? Sometimes I like to let people see the full path even if it is long, for transparency sake...

**Comment by vmbrasseur** [comment]
Google is killing off its URL shortener. I recommend against using it.

**Comment by raynamharris** [comment]
We've been using bit.ly quite well. Will close this issue.
