### ISSUE TITLE
Jekyll site template for future websites

### ISSUE THREAD

**Issue by charlesreid1** [dcppc/dcppc-workshops#35]
Just a note here following up on dcppc/2018-may-workshop#2 and the Jekyll site.

I created a "seed" repo called [magic-flying-camel](https://github.com/charlesreid1/magic-flying-camel) that contains the materials needed to get a simple static site up and running. (We can also fork this repo and create a new seed repo that contains workshop-specific modifications to the base template, e.g. in dcppc/workshop-jekyll-seed if silly names is not your thing). 

To use magic-flying-camel, the `docs/` folder contains all the files you need for a Github Pages Jekyll site. You can copy the entire `docs/` folder into your own repo's `docs/` folder, then modify `_config.yml` to set site-specific information (there are about 5 or 6 lines to change, mainly URLs. This has room for improvement.) Commit the `docs/` folder.

You'll also need to adjust the settings of the repository: Settings > Github Pages and pick Source > "Master branch docs/ folder". This tells Github you have a Jekyll site in the `docs/` folder. Github will use Jekyll to turn your pile of HTML templates and markdown files in `docs/` into a full-fledged static HTML site, available at `https://<your-org>.github.io/<your-repo>`

<img width="818" alt="screen shot 2018-05-11 at 01 53 09" src="https://user-images.githubusercontent.com/368075/39915952-26af2ac6-54be-11e8-8729-2f8b2d9575bf.png">

**Comment by charlesreid1** [comment]
Example workflow:

Suppose I'm running the December 1999 DCPPC Workshop. I would:

Create `dcppc/1999-december-workshop` repo on Github

```
git clone https://github.com/dcppc/1999-december-workshop.git
git clone https://github.com/charlesreid1/magic-flying-camel.git
cp -r magic-flying-camel/docs 1999-december-workshop/docs
cd 1999-december-workshop
vim docs/_config.yml    # and set site specific settings
git add docs/ && git commit docs/ -m 'Initial commit of Jekyll site' && git push origin master
```

Then adjust the settings of the 1999-december-workshop repository to create a Github Pages page from the `docs/` folder.

**Comment by raynamharris** [comment]
Alternatively, now that we have created a few workshop websites, once can use this alternative approach:

- clone an old workshop website repo (e.g. 2018-june-workshop using `git clone https://github.com/dcppc/2018-june-workshop.git`)
- copy all the contents to a new workshop website directory (e.g `cp -r 2018-june-workshop/ 2018-july-workshop/`)
- navigate to the new directory
- delete the .git/ directory using `rm -r .git`
- modify all the files in docs/ to replace old workshop details with new workshop details
- modify the .config file, replacing old workshop details with new workshop details
- initialize the new repo by running `git init` 
- visit https://github.com/dcppc and create a new repository with the same name
- follow the instructions to add, commit, and push your local files to the remote repository
- in the repo Settings, select the option to use the docs/ folder to create a public website

**Comment by raynamharris** [comment]
We might want to migrate this documentation to a file, but for now, I'll mark this done and close the issue. I'll link here for anyway looking for ways to create a workshop website.
