### ISSUE TITLE
reserve rooms

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#39]
We have 4 rooms confirmed:
- [x] Lahey Room -- flexible rectangle desk arrangements for 50 people (main room?)
- [x] Room 423 -- flexible desk arrangements for 15-20 people (breakout 1)
- [x] Room 320 -- flexible desk arrangements for 15-20 people (breakout 2)
- [x] Ballard -- larger room (social room?)
- [x] Room 403 -- larger room (quiet room?)

We need these additional rooms:
- [x] room for ~10 person conference call during lunch on May 31 for Calcium, Helium, and Argon (which, now that I think about it, it might be nice to have a room like this reserved for the whole time...)

**Comment by raynamharris** [comment]
Related to #10
The Lahey room should be set up for presentations, video recording, and audio. 
The breakout rooms should probably also have a projector and monitors.

**Comment by vmbrasseur** [comment]
As we're over halfway through the second day of the workshop, it's probably OK to close this one. ;-)
