### ISSUE TITLE
Name tags for attendees

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#42]
We need name tags for attendees.

These should include:

* Name
* Affiliation
* Team name

**Comment by vmbrasseur** [comment]
Meredith is going to help with this. Wooo! 🎉

**Comment by ctb** [comment]
please let's restrict this spreadsheet to consortium members if possible.

**Comment by raynamharris** [comment]
Link to spreadsheet removed. 
@ctb, should I change the repo to private but add it to team everyone so that all consortium members have read access?

**Comment by meredithlgamble** [comment]
Thanks! I will print this for tomorrow.
