### ISSUE TITLE
setup zoom for "live streaming" the morning sessions

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#44]
I've had a least two requests to a webcast or live stream for the event. 
Zoom was recommended

**Comment by raynamharris** [comment]
I set up two 3.5 hour zoom events for both mornings form 8:45 - 12:15

*May 30*
Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/229187879
Or iPhone one-tap :
    US: +16468769923,,229187879#  or +16699006833,,229187879# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 876 9923  or +1 669 900 6833  or +1 408 740 3766 
    Meeting ID: 229 187 879
    International numbers available: https://zoom.us/u/b1wdktIml

*May 31*
Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/723283404

Or iPhone one-tap :
    US: +14087403766,,723283404#  or +16468769923,,723283404# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 408 740 3766  or +1 646 876 9923  or +1 669 900 6833 
    Meeting ID: 723 283 404
    International numbers available: https://zoom.us/u/bIWdjTk3F

**Comment by raynamharris** [comment]
If everyone is cool with this, I can post the info on the website and also in an issue in the may workshop repo. I'm open to other suggestions though if someone this a platform other than zoom is better

**Comment by karenword** [comment]
If @ctb is bringing the Chromebox setup, we'll just want to be sure that's ready to go with Zoom.

**Comment by raynamharris** [comment]
If the chromebox is setup for something else, we can go with that.

**Comment by ctb** [comment]
works with zoom.
On Tue, May 22, 2018 at 01:29:22PM -0700, Rayna M Harris wrote:
> If the chromebox is setup for something else, we can go with that. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dcppc/dcppc-workshops/issues/44#issuecomment-391129917
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ctb** [comment]
it works with zoom. am I the only person coming from Davis? So I would
need to bring the chromebox? I'm leaving early the second day so someone
else would need to bring it back (or mail it back).

**Comment by karenword** [comment]
Becca may be the only other person traveling from Davis. It sounds like they may also have an acceptable setup on site, so it may be possible to skip the equipment for this particular workshop if it causes trouble.

**Comment by ctb** [comment]
ok - let me know.

**Comment by raynamharris** [comment]
Harvard is setup to use webex. That is what y'all used for the last f2f meeting so that should work 

(See https://github.com/dcppc/dcppc-workshops/issues/10 for AV details)

**Comment by vmbrasseur** [comment]
@raynamharris I'm pretty well pegged this afternoon, but I can probably spare a few minutes in there to be the remote tester for a streaming setup.

**Comment by vmbrasseur** [comment]
@raynamharris totally nailed this one. ❤️
