### ISSUE TITLE
update reimbursement items

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#45]
Gathering new details here to be included. this is a brief summary
- [x] extended stays - allowed, provide flight comparison for shorter days
- [x] purchasing tickets for others -  not allow
- [x] hotels - no pre-approval for non-UC davis employees
- [x] add a new a section for reimbursement for catering and budget
- [x] special requests

**Comment by karenword** [comment]
For catering, Jason will need itemized receipts as well as a list of participants to process reimbursement.

**Comment by raynamharris** [comment]
add this to https://github.com/dcppc/organize

**Comment by raynamharris** [comment]
The reimbursement page(s) need updating as we learn more. These are things we learned from the [June workshop](https://github.com/dcppc/2018-june-workshop). Will be easier to keep up with change info by moving the reimbursement instructors out of workshop repositories and into organize.

- detailed UC Davis travel policy: https://policy.ucop.edu/doc/3420365/BFB-G-28
- hotels can't exceed $275/night (must include price comparison if they do)
- We are not able to reimburse 3rd parties. All expenses will be reimbursed directly to the DCPPC-affiliated person filing the claim, and this person can pay back the company/institution for costs incurred.
- cannot pay for seat upgrades for flights
- For foreign travellers-  Report the currency paid, our reimbursement system will handle the conversion to dollars
- For foreign travellers -We can do wire transfers. We need the reimbursement currency, USD, bank name, bank address, BIC or routing number, account number, name on the account, address of the beneficiary, and IBAN number.

**Comment by raynamharris** [comment]
With every workshop we learn something new. This PR https://github.com/dcppc/2018-september-workshop/pull/21 add a recommended 45 day limit for filing for reimbursement and the meal allowance numbers for catering

**Comment by ctb** [comment]
yes pls
