### ISSUE TITLE
make and send agenda to NIH folk  - July meeting

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#47]
NIH needs a draft agenda and list of ~4 recommended hotels as early as possible. 
See this doc as a template: https://docs.google.com/document/d/1yaT87a2r7rDWdNYXLSwGUpi8n1n_a9NiML3Z4m6sxZ4/mobilebasic?usp=gmail

**Comment by vmbrasseur** [comment]
My suspicion is that the May agenda will work as a good first draft for July for now, if they need something ASAP.

**Comment by raynamharris** [comment]
Yes, the actual "agenda" part is the same for the May, June, and July workshops. The missing piece is the dates and building information.

**Comment by raynamharris** [comment]
done see https://github.com/dcppc/dcppc-workshops/pull/70
