### ISSUE TITLE
Twitter strategy for the May workshop

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#49]
1. What's the official hashtag for this event? We should ask attendees to use it & to tweet about the event.
1. What's our twitter strategy for the event in general? I would like to hand out login information to a few Team Copper folks who'll be onsite so they can do some real-time twittering.

**Comment by raynamharris** [comment]
I would like the login information. I'll do some tweeting and retweeting.

**Comment by raynamharris** [comment]
#CommonsPilot is what people used at the first face to face. I say we keep using this one.

**Comment by raynamharris** [comment]
@nih_dcppc is our account. @NIH_CommonFund and @NIHDataScience are two official NIH accounts that sometimes tweet about us.

**Comment by vmbrasseur** [comment]
I PM'd the login credentials to @raynamharris on Slack.

**Comment by raynamharris** [comment]
Tweet strategy executed. tweets posted had `#commonspilot` as the hashtag
