### ISSUE TITLE
Make intro slides

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#52]
* Wifi info
* Slack channel
* CoC
* Link to the Workshop Google Drive Folder

**Comment by raynamharris** [comment]
Done https://docs.google.com/presentation/d/1DH33vQI-2CGVxLu0DF0h7N04lzBPEI7W-EWH4VwT8TM/edit?usp=sharing

Feel free to edit

**Comment by raynamharris** [comment]
now set to auto-advance every 5 seconds and loop https://docs.google.com/presentation/d/e/2PACX-1vRFuHKYefqgezcmGAi39TvHG95oWh8us_wvpz-14wbxrMdKfxSigk5tB_vMkFC0tJt_1V9Sm0UVTtru/pub?start=false&loop=true&delayms=5000

**Comment by vmbrasseur** [comment]
Since it's well past the intro time, I'll close this issue.

Rayna++.
