### ISSUE TITLE
Dates/location for July workshop at RENCI

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#53]
From Sarah Davis to our team email alias:

> ​Sasha, Stan and I talked after you spoke with him. Thursday/Friday, July 26-27 is what we are currently thinking. July 25-26 (Wednesday/Thursday), July 27-28 (Friday/Saturday), July 31-Aug 1 (Tuesday/Wednesday) are all two-day periods that work for RENCI. And if they don't work, we also have flexibility from July 16-24. 
>
> > I have the main conference room reserved for July 16-27 and again on July 31-Aug 1, so let me get a few other good days after talking with our ED (Stan). I'll try to get back to you tonight. .

**Comment by ctb** [comment]
(it'd be great to get these dates out to vivien and the consortium as quickly as possible - maybe a doodle to assess general availability?)

**Comment by raynamharris** [comment]
Doodle poll created https://doodle.com/poll/9sigc7mensz2eggm

**Comment by raynamharris** [comment]
This is the status of the doodle poll so far.

@davissn30 Are we okay to choose Wednesday/Thursday as the final dates?

![screen shot 2018-06-06 at 9 54 33 am](https://user-images.githubusercontent.com/7544197/41046276-c2db5922-696f-11e8-9375-95db75b46307.png)

**Comment by davissn30** [comment]
Works for us!

**Comment by raynamharris** [comment]
Excellent! I'll start updating in all the relevant places.

**Comment by davissn30** [comment]
@raynamharris do you have an approximate # so we can get a room block. I assume around 50?

**Comment by raynamharris** [comment]
@davissn30 we had 55 as the last one so 50 is a good estimate

**Comment by raynamharris** [comment]
We can cap registration to fit the size of the main room

**Comment by davissn30** [comment]
We can easily fit 60, but can always squeeze more in.
