### ISSUE TITLE
Date/Location for September meeting in Boston Sept 20 - 21

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#54]
Mercè has enthusiastically offered to host the meeting at Harvard.  Dates that work are:

Preferred: M-F the week of September 17
Second: M-F the week of September 10

**Comment by raynamharris** [comment]
Here is a doodle poll with those dates. _Note_ I also included an option for the last week in case there is a strong opinion that the meeting should be hosted that week, with the caveat that Mercè will not be able to host. 

https://doodle.com/poll/erq3rgv2saqfhknx

**Comment by ctb** [comment]
...shall I send this out on Monday?

**Comment by vmbrasseur** [comment]
Will there be a problem with this one being near the middle of the month rather than the end? Will it fall too close to the August workshop dates?

**Comment by vmbrasseur** [comment]
Ah! Yeah, that's perfect! Woo!

**Comment by ctb** [comment]
Hi folks, I have been alerted that this is Yom Kippur, which is "the most significant religious holiday of the year", sundown Sep 18-19. I think we need to reschedule.

**Comment by vmbrasseur** [comment]
YIKES! Oh, wow, good catch whoever told Titus that. Yeah, that would be very bad.

**Comment by raynamharris** [comment]
So, the option of Sept 20-21 (Thursday - Friday) is out because it would require travel on the 19th?

**Comment by raynamharris** [comment]
If we scratch the week of the 17th as an option, Mercè is only available to host on the week of the 10th. We would need to find an alternate host if we push to the week of the 24th.

**Comment by mercecrosas** [comment]
How about:
Sept 13 - 14
Sept 20 - 21 (just after Yom Kippur)
?

I think that even if I (or someone else) could arrange to host it the last week of September, it falls to close to the October 16 NIH meeting.

**Comment by raynamharris** [comment]
12 out of 14 people have responded to the current poll say they can attend a meeting on Sept 20 - 21

So, we have 3 options given @mercecrosas response above
- go with Sept 20 - 21 knowing that the two previous days are important holidays
- go with Sept 13 - 14 without polling to see if it's a good fit
- start a new poll or send out some feelers to see which is the least-worst option

**Comment by mercecrosas** [comment]
👍 
Thanks @raynamharris - it works for me. How many people attend to these workshops? What should we plan for? I'll need to check for rooms at Harvard and reserve them as soon as possible before they are taken.

**Comment by raynamharris** [comment]
Thanks, @mercecrosas! I would plan on ~60 people for the main room and a few smaller rooms for breakouts.
