### ISSUE TITLE
reconcile who will attend "collaboration fest" and who will attend "June workshop"

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#57]
The backstory:
- In the "save the date" June email (https://github.com/dcppc/dcppc-workshops/blob/master/draft-emails/june-savethedate.md) I encourage all hopeful June-workshop attendees to sign up for "collaboration fest"
- During the may workshop, it became clear that some people want to attend 2-day hackathon only (aka collaboration fest) but we still need to have a June workshop that follows the format of the may workshop

How do we reconcile this?

**Comment by vmbrasseur** [comment]
Does it have to be 2 days?

Could we just tack an extra day on the end for those who wish to do the hackathon thing?

Regardless, maybe there's another location that can give us some space and folks can self-organise after that? SE Lucky Lab (family-friendly restaurant/pub) has a big room they can rent out/reserve (or just their main space is good; lots of plugs). They also have good wifi, food, drinks, parking, and is dog friendly ;-). Friends have held impromptu hackathons there many times. The library may have rooms available, but that's just a guess based on the tendency of libraries to have that sort of thing. :-)

**Comment by ctb** [comment]
+1

**Comment by davissn30** [comment]
Teams Helium, Argon, Calcium (and I believe Xenon) have discussed the need for a 2-day hackathon and the workshop was a good time to have it since many of the personnel will overlap. So tacking one day on at the end doesn't serve the purpose (also, that's a Sunday and people need at least one day off). These teams will be sending specific personnel for the hackathon portion that may not be as interested in the general topics of the main meeting track. Any thoughts @briandoconnor @cricketsloan @clarisca @alisonleaf @rpwagner

**Comment by raynamharris** [comment]
Thanks, @davissn30, this is very useful, and thanks for pinging the others! 

What if we have everyone socialize together at the welcome remarks, end of the day recaps, closing remarks, coffee breaks, and lunch? Other that attendees can split off into whatever is most useful for them and for the DCPPC (hackathon all day, hackathon in lieu of the breakout sessions, workshop only). Does that make sense?

Either way, I highly recommend Lucky Lab for dinner and drinks on the first evening 👍

**Comment by cricketsloan** [comment]
I agree that beginning and end collections will be appropriate, but then we should let the hackathon spin off happen and people who are interested in any of the issues:

* sharing workflows
* auth
* DOS

can join them.  We can also have them report back.

**Comment by rpwagner** [comment]
My expectation is that there is enough work in terms of development activities and project planning to cover everyone. I agree with @cricketsloan  that limiting the amount of time developers are in full sessions vs. coding.

To be more specific about the topics, I recall discussing the following for the areas Cricket mentions (we could open these up for more input before the meeting):

* Workflows: primarily about creating reusable validations tools (scripts,  containers) that can be used to assess whether or not different implementations of the same workflow are producing the expected results.
* DOS+BDBags: What is the relationship between the DOS API and BDBags as interoperable data access and exchange standards?
* Auth: Working implementations of REST APIs supporting the OAuth/OIDC federation model.

These would dovetail very well into the [4M.4.FULLSTACKS: Cross-stack Compute] (https://github.com/dcppc/dcppc-deliverables/issues/45) deliverable.

**Comment by raynamharris** [comment]
Okay, I have attempted to combine all this info into the agenda. Let me know if this looks good @davissn30 @cricketsloan @rpwagner. Feel free to modify PR https://github.com/dcppc/2018-june-workshop/pull/3/files

**Comment by vmbrasseur** [comment]
Looks like this has rolled out. Any objections if I close it, @raynamharris, or is there still work left?

**Comment by raynamharris** [comment]
Okay to close, I've been working with Brad and another CoFest organizer the CoFest people have all the info they need.

**Comment by raynamharris** [comment]
reopening for 1 second. 

participant count: 
- 18 workshop only
- 2 hackathon only
- 19 combination of both
- 2 NA
