### ISSUE TITLE
create ti.to registration page for June workshop

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#58]
ti.to for registration worked very well for the may workshop

We should 
- [x] create a June workshop registration page with ti.to, mirroring the form used for the may workshop
- [x] add a question to collect their twitter handle (as per #50)
- [ ] update the June website to link to the appropriate registration page (http://nih-data-commons.us/2018-june-workshop/)

**Comment by vmbrasseur** [comment]
Tito event created: https://ti.to/dcppc/june-data-commons-workshop

I was about to update the June Workshop webpage in https://github.com/dcppc/2018-june-workshop but it's not clear whether I update index.md or the YAML file so, yeah, I haven't done that. :-)

**Comment by raynamharris** [comment]
Thanks @vmbrasseur. 

In short, ` index.md` should be updated as that is where the information that populates the home page is stored. The README _does_ mention the YAML file, so I understand your confusion, but the YAML file is related more to the look and feel of the website than the actual text that is displayed.

**Comment by raynamharris** [comment]
Would anyone else on Team Copper like to update the June website to link to the appropriate registration page? Perhaps after watching my not-so-fabulous screencast linked in #62

**Comment by raynamharris** [comment]
Also, should we add questions about 
1. whether or not they officially registered for collaborationfest
1. the extent to which they want to participate in the hackathon (not at all, in lieu of the breakout sessions, all hackathon all day, some combination)?

Relates to https://github.com/dcppc/dcppc-workshops/issues/57

**Comment by vmbrasseur** [comment]
I made some minor edits to the new questions but it's now good to go!

**Comment by raynamharris** [comment]
registration launched!
