### ISSUE TITLE
update agenda

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#59]
We should:
- [x] add an agenda to the website (https://github.com/dcppc/2018-june-workshop/blob/master/docs/agenda.md)
- [x] email DCPPC with the agenda

We can use the [may workshop agenda](https://github.com/dcppc/2018-may-workshop/blob/master/docs/agenda.md) as a template and/or this ["draft" template](https://docs.google.com/document/d/1yaT87a2r7rDWdNYXLSwGUpi8n1n_a9NiML3Z4m6sxZ4/edit) that was sent to NIH and/or a variation of those two

**Comment by raynamharris** [comment]
See https://github.com/dcppc/2018-june-workshop/pull/3

**Comment by vmbrasseur** [comment]
Hello, @raynamharris! It looks like this is all rolled out now? Any objections to my closing the issue, or is there still work left?

**Comment by raynamharris** [comment]
Actually, its not quite ready yet. Need to discuss at today's meeting.

**Comment by raynamharris** [comment]
From the oranizers at BOSC:

> Practically, I'd love to coordinate with you on your schedule and plans so
you can overlap with the main CoFest meetings. We'll plan to have short 1/2
hour all group discussions at least twice a day (probably start and end of day)
where each group (or cluster) will present their ideas for what they're going
to work on and also accomplishments in a short no slides talk. Will that fit
with your plans? It will really help give visibility to the work you're doing,
get other people excited about the commons, and hopefully draw some
programmers to your event.

**Question**
Should we scratch our DCPPC-specific welcome and closing talks and have everyone attend the larger CoFest welcome and closing talks?

**Comment by raynamharris** [comment]
Thanks, Vicki, current plan: keep workshop agenda as planned. Send DCPPC representative (@awz) to opening and closing talk.
