### ISSUE TITLE
create screencast illustrating GitHub workflow

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#62]
Rationale: Learning how to use GitHub repositories, issues, pull request, project boards, and websites is non-trivial.  Documenting some of these things as screencasts will be a nice supplement to the "how to run a workshop" document proposed in #61

**Comment by raynamharris** [comment]
Here is version 1: https://youtu.be/21qCXsxYoQo

It is way too long (13 minutes). This is partly because, during the middle of the video, I realized that only @vmbrasseur and @raynamharris have write access to this repo. (This means that the two of us are the only users who can 1) move issues onto the project board, 2) add labels, 3) assign issues to people, and 4) merge pull requests. However, that should be the subject of another issue)

Nevertheless, it would be great if @sedrie @meredithlgamble could watch this and let me know if it is useful.

**Comment by sedrie** [comment]
This is GREAT! Helpful to see where things are and how to do them. Thanks @raynamharris

**Comment by raynamharris** [comment]
It's not a flawless video, and I feel like I should learn how to trim out middle parts of videos first, but I'm +1 for posting not-quite-perfect videos now and in case it takes me a while to get the edited version up.

**Comment by vmbrasseur** [comment]
Kk. I'll get this up to IA when I'm not on hotel wifi. 😉

**Comment by sedrie** [comment]
yup - I approve :-)

**Comment by vmbrasseur** [comment]
It'll take a little while for transcoding to complete, but [this is now on Internet Archive](https://archive.org/details/HowToCreateAndIssueAndSubmitAPullRequest21qCXsxYoQo).

**Comment by raynamharris** [comment]
Thanks @vmbrasseur
