### ISSUE TITLE
help with reimbursement page

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#64]
I was trying to fix a broken link to the reimbursement workshop on the reimbursement page of the June workshop. While I was there I decided to update the reimbursement page with all the details I learned from the may workshop. I meant to submit to submit a PR, but I accidentally push. And now. all the reimbursement links are broken :(

http://nih-data-commons.us/2018-june-workshop/

@charlesreid1 any idea what I have done wrong?

**Comment by charlesreid1** [comment]
Looking into this now...

**Comment by charlesreid1** [comment]
Fixed 👍 

Problem was with the YAML header. It was turning the reimbursements page into an HTML file that was not named `index.html` so when you went to `reimbursements/` there was no default page to display.
