### ISSUE TITLE
reserve rooms for July workshop

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#65]
we should reserve rooms the following rooms
- [x] 1 large main room tables and chairs for _at least_ 50 people
- [x] multiple (2-4?) smaller breakout rooms
- [x] space for serving coffee and lunch
- [x] space for eating lunch

also needed 
- [x] description of or link to building accessibility
- [x] assistance getting guest passes if needed
- [x] description of how to log on to the wifi
- [x] extension cords or sufficient power outlets

optional
- [x] fancy equipment for AV

Please describe accommodations in the comments

**Comment by raynamharris** [comment]
Does this make sense @davissn30 ?

**Comment by davissn30** [comment]
Rayna -

Here is a draft welcome packet for the workshop at RENCI. [https://drive.google.com/open?id=1Xogm_RKWGGL9LCw2mRlOMwixPzUDg_zQ](url). It includes conference room info, hotel info, restaurant info, and directions. I will add to it as I get more information (e.g., once we get the room block set up at the Sheraton). 

Re: fancy equipment, our large conference room, Biltmore, has projectors (connects to room computer or laptops), microphones (hand-held, lavalier, and table top), a podium. The tables have 2 outlets per table (we'll likely have 3 people per table). What else might we need? The smaller conference rooms  all have projectors, room computers, a few plugs at the conference table. 

Re: accessibility, do you mean ADA accessibility? There are ADA automatic doors on the 2nd/main floor with easy access to RENCI on the 5th floor via an elevator. 

There is Wi-Fi throughout the building and the password is posted in every conference room. 

There is no problem getting in and out of the building during normal business hours and we will have signs directing people to our offices.

**Comment by davissn30** [comment]
@raynamharris Are we official for 25-26. I would like to release my hold all the conference rooms for the other days we were eyeing. I've been a real room hog. :)

**Comment by davissn30** [comment]
[DCPPC long Welcome Packet .docx](https://github.com/dcppc/dcppc-workshops/files/2080742/DCPPC.long.Welcome.Packet.docx)

**Comment by raynamharris** [comment]
Hi @davissn30 This is awesome! We are officially good to go for 25-26!

**Comment by raynamharris** [comment]
reserved rooms include:

Room | Location | Capacity
-- | -- | --
Biltmore Conference Room | 5th floor | 60
DaVinci Conference Room | 5th floor | 17
Sandburg Conference Room | 5th floor | 14
Fishbowl Conference Room | 5th floor | 14
Dogwood Conference Room | 1st Floor | 10
