### ISSUE TITLE
meals for July workshop

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#66]
We have a $62 per person per day budget for food. This includes all catered and individually purchased food. 

**Catering**
We recommend a budget of $14 per person for 2 coffee breaks and $15 per person for lunch. 
Team Copper will send an overview of dietary restrictions of attendees.

**Non-catered options**
Having a reservation for ~2/3 of attendees for dinner for the evening of Day 1 is awesome. Recommendations for breakfast and dinner on other days is welcome! 

**Reimbursement**
Please keep an itemized receipt for all food purchases. Submit the receipt with a list of attendees to Team Copper

**Comment by davissn30** [comment]
https://github.com/raynamharris when you create the registration form for this event, can you include a question about attending dinner on July 25? We will likely arrange for something on Franklin Street (which is a more happening part of town than where we are) and I’d like to have some idea of numbers. Thanks!

**Comment by raynamharris** [comment]
Question added!

**Comment by davissn30** [comment]
https://github.com/raynamharris Another question: for the dinner on the Wednesday, most of the restaurants in the “fun” part of town won’t allow individuals to pay separately. Is it possible for RENCI to pay for dinner attendees and get reimbursed (ie like lunch and break costs) or is that needlessly complicated. Thanks!

**Comment by raynamharris** [comment]
Yes! As long as we submit a list of attendees with the itemized receipt. We can't reimburse alcohol, so that must be on a separate check.

**Comment by davissn30** [comment]
I love it when people's answers make my life easier. Thanks again.

**Comment by davissn30** [comment]
@raynamharris, FYI, there are not great breakfast options in the immediate vicinity to RENCI (just the Sheraton and a McDonalds). So we will offer a light breakfast here at RENCI (bagels/muffins, yogurt, fruit). We should still be staying well within the budgeted amount. 

Wednesday est. per person total | $17.33
Breakfast | $2.97
Lunch | $12.57
Snack | $1.79
(Available for Dinner | $44.67)

Thursday est. per person total | $21.10
Breakfast | $4.88
Lunch | $14.43
Snack | $1.79
(Available for dinner | $40.90)

**Comment by raynamharris** [comment]
Thanks @davissn30 This is great news!

**Comment by davissn30** [comment]
Estimates for Food Costs for July Workshop [https://docs.google.com/spreadsheets/d/1hGaNYsH0ZytBJV_egEzWDEwB5LecTDUuUZiJgQNzGek/edit#gid=2136446595](url)

**Comment by raynamharris** [comment]
Current numbers:

Number registered: 57!

Diet | Count 
--- | ---
No restrictions  |  47    
Keto diet  |   1
no pork or bacon   |  1
No peanuts  |   1
Vegan   |   3 
Vegetarian   |  4

Count for Wed. dinner

Option | Count 
--- | ---
Yes |  42
NA | 3
Unsure |  11
No | 1

**Comment by raynamharris** [comment]
Meals were a huge success! Thanks @davissn30 and Team Helium for the excellent job with catering and dinner planning.
