### ISSUE TITLE
create ti.to registration page for July workshop

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#67]
ti.to for registration worked very well for the may workshop

We should 
- [x] create a workshop registration page with ti.to, mirroring the form used for the may workshop
- [x] add a question to collect their twitter handle (as per #50)
- [x] add link to registration page on workshop website (http://nih-data-commons.us/2018-july-workshop/)

**Comment by raynamharris** [comment]
Done! https://ti.to/dcppc/2018-july-workshop

@vmbrasseur Can you give it a look over?

ti.tio did not like the address (100 Europa Drive,  Chapel Hill, NC 27517)

**Comment by vmbrasseur** [comment]
Looks good! And there are already 14 registrations, so I'm guessing this one's live. I'll close the issue.
