### ISSUE TITLE
June Workshop: CollaborationFest is SOLD OUT - can't register 

### ISSUE THREAD

**Issue by KCB13** [dcppc/dcppc-workshops#71]
I was (dutifully) trying to follow the instructions while registering for the June F2F, and couldn't register to CollaborationFest as it is already sold out. @raynamharris any thoughts?

**Comment by raynamharris** [comment]
Thank you @KCB13. we are working with the organizers to get this opened up again. I'll let you know when its back up

**Comment by AviMaayan** [comment]
I think it is fixed now...

**Comment by raynamharris** [comment]
Thanks, @AviMaayan! Yes, registration is back up so you can register now @KCB13
