### ISSUE TITLE
June Workshop link to Sitka Block of Reed campus leads to Page Not Found

### ISSUE THREAD

**Issue by KCB13** [dcppc/dcppc-workshops#72]
Looking at accommodations through the [June 2018 DCPPC Workshop webpage](http://nih-data-commons.us/2018-june-workshop/) and tried to click on: 

"Lodging in the Sitka Block of Reed campus is available for attendees without children. Reserve your spot at https://galaxyproject.org/events/gccbosc2018/venue/."

Which led to a Page Not Found.

**Comment by KCB13** [comment]
I think on the website version there is a ']' in the link that is leading to my error.

**Comment by raynamharris** [comment]
Thanks @KCB13! You were correct!
