### ISSUE TITLE
confirm rooms for June workshop

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#73]
here's the scoop that I have on rooms for the june workshop

- One large space for whole CoFest meetings
- An auditorium for Data Commons that holds up to 100. Great for talks and discussions.
- 12 tables with 10 chairs each spread out around the building -- 4 tables per floor
- 3 general purpose classrooms for groups of 10-20 to meet quietly

Still need to get room numbers and figure out where people will be during the meeting

**Comment by raynamharris** [comment]
From [CoFest website](https://galaxyproject.org/events/gccbosc2018/collaboration/)
> CollaborationFest will take place in the Performing Arts Building, which features multiple meeting rooms, common spaces, and a unique 3 storey atrium that we will make maximal use of for gathering and collaborating.

**Comment by raynamharris** [comment]
Need to 
- [ ] add accessibility 
- [ ] add rooms to our website

**Comment by vmbrasseur** [comment]
We have an email asking which specific building the workshop will be occurring.

Will all events be in the Performing Arts Building, or just the CollaborationFest?

**Comment by raynamharris** [comment]
All events/rooms will be in the Performing Arts Building

**Comment by raynamharris** [comment]
For the june workshop, we used:

PAB320 - morning talks, breakout session planning, and afternoon recaps
PAB131 -  FullStacks hackathon
open seating in foyer and outdoor patio - breakout sessions
