### ISSUE TITLE
assign roles for June workshop

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#75]
We need some people dedicated to the following
- [x] note taking - that should occur in each breakout session, one person per breakout group
- [x] google drive manager - Rayna - include links in email today
- [x] MC - Rayna on Friday, Edrie on Saturday
- [x] slack - anyone on team copper on slack
- [x] twitter -- Sasha
- [x] intro talks - Sasha will give 5 minute spiel for CoFest and Rayna will do DCPPC intro 
- [x] welcome/motivational talk? - Edrie will present 1 video from May workshop
- [x] closing - Rayna on Friday, Edrie on Saturday

**Comment by vmbrasseur** [comment]
Note taking is something that should occur in each breakout session, so more than one person will be needed.
