### ISSUE TITLE
reserve rooms workshop on October 15-16

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#83]
**Background** We are going to run a two-day oct f2f meeting, Oct 15-16, in Bethesda to collocate with the October 16th NIH meeting. We can plan for 100 people meeting for the first day? The first day will be an unconference as usual with everyone attending. On the second day, we will split up, with people attending either the NIH meeting (PIs and others, by invitation only) or staying at the “regular f2f” meeting.

**needed**
- [ ] venue for 100 (classroom or auditorium seating) with at least 2 concurrent breakouts (ideally rooms with round tables and whiteboards)
- [ ] catering: lunch and snacks
- [ ] in Bethesda

**potential venues**
I found a handful of venues that have 100 person capacity and a listed price for the rental. http://www.evenues.com/Meeting-Spaces/Bethesda/Maryland/?id=cf69f321-f65d-4144-bffd-ff0a603f985d

**Venues won't work**
- ~~~Friends Meeting of Washington, $400 daily~~~ too small
- ~~~Arlington Court Suites, $450 daily~~~ to far away
- ~~~Hyatt Regency~~~
- ~~~Hilton Garen Inn $1000 daily (85 people max)~~~
- ~~~AvantEdge Workspaces, $1000 daily (high tech friendly)~~~
- ~~~Marriott 5151 Pooks Hill Rd, Bethesda, MD 20814~~~ full
- ~~~Bethesda North Marriott Hotel & Conference Center - waiting to hear back~~~ full
- ~~~Davinci meeting and workspace~~~ too small
- ~~~Strathmore~~~ not available on the 15
- ~~~National Archives~~~ not available on the 15

**venues to call**
- Congressional Cemetery Chapel, $300 hourly
- Digital studio $3000 daily (meant for video production)
- FHI360
- AAAS
- Holiday Inn Washington--550 C St SW
- Ronald Reagan Building**requires security screen so not as easy
- Washington Plaza Hotel
- 1776 building

**Comment by ctb** [comment]
I like the Hilton Garden Inn - it's close to the NIH, so we could have people
stay there for both meetings.

Could you look into that more closely and see if we can get a marker down
for both days? I can supply a credit card if need be.

best,
--titus

**Comment by raynamharris** [comment]
okay, left message and filled out an event request form. Will follow up later today.

**Comment by ctb** [comment]
thx!

**Comment by raynamharris** [comment]
Hilton Garden Inn can only accommodate 85 people. We would have to reserve all three rooms.
- room 1 - capacity: capacity 100 sq ft. theater 85 people 
- room 2 - capacity 500 sq ft. dinner setting 48 
- room 3 - boardroom for 10 people

Will check on the Hyatt Regency tomorrow (to follow up on a recommendation and inquiry from today)

**Comment by raynamharris** [comment]
The Hyatt Regency is fully booked on Mon-Tues, Oct 15-16 (but does have space on Wed-Thurs if we are flexible about dates...)

**Comment by jyttri** [comment]
Other suggestions:
BETHESDA area (near NIH):
Strathmore?

DOWNTOWN:
FHI360
Want to go a museum route? National Archives?
AAAS
Holiday Inn Washington--550 C St SW
Ronald Reagan Building**requires security screen so not as easy
Washington Plaza Hotel
1776 building

**Comment by raynamharris** [comment]
Thanks @jyttri, I sent an email to Strathmore and National Archives. I'll make my way through the list!

**Comment by arieberman** [comment]
Just in case it is helpful, both the Bethesda Marriott (Pooks Hill Rd) and the North Bethesda Marriott have large conference centers. North Bethesda is more convenient from the Metro and walkable restaurants.

**Comment by raynamharris** [comment]
Thanks @arieberman. Unfortunately, both Marriott's are already booked

**Comment by raynamharris** [comment]
Team Copper is no longer in organizing any side workshop in Bethesda.

For the NIH meeting on Oct 16th, NIH is still determining who will need to attend. A contractor working on travel info who will handle informing everyone who is invited about hotel arrangements. Wanted y'all to know in case you get more questions.

Please contact @jyttri with questions or concerns.
