### ISSUE TITLE
Set general schedule/format

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#9]
General idea so far:

* Two days
    * Day 1: Focus on progress so far
    * Day 2: Focus on plans for the future
* Basic format
    * Brief intro
    * Introductions & progress report by each team ("Tell us who you are and what you've been doing, in 5 minutes")
    * Organise unconference schedule
    * Lunch
    * Unconference sessions
    * Reconvene for session recaps
    * Closing remarks

Open questions:

- [x] Who's going to do the intro, MC lightning talks, facilitate unconference scheduling, MC recaps, give closing remarks? (doesn't all have to be the same person)
- [x] Do we have catering for lunch or are people on their own? (Issue #14)
- [x] Do we have catering for morning/afternoon breaks? (Issue #14)
- [x] How many concurrent unconference sessions will we have? (depends on the space we have)
- [x] …what else?

**Comment by raynamharris** [comment]
Vicki, currently I don't have this basic schedule on the agenda, but I think it would help with some questions. Should we use "breakout groups" instead of "unconference" as our terminlogy? Maybe like this:

### Basic format
- Welcome
- Introductions 
- Short team updates
- Organize breakout groups
- Lunch
- Breakout groups
- Reconvene for session recaps
- Closing remarks

**Comment by vmbrasseur** [comment]
If you think that'll be less confusing for the audience, sure.

**Comment by vmbrasseur** [comment]
Also, a big 👍 to having the basic schedule on the website.

**Comment by raynamharris** [comment]
How about something a little more detailed? What adjustments should be made, if any?

May 30, 2018
09:00 : Welcome
09:15 : Opening talk
10:15 : DCPPC operations: project management and demos
11:00 : Planning for breakout groups
12:00 : Lunch
12:30 : Breakout groups: 
16:00 : Debriefing
16:50 : Closing

May 31, 2018
09:00 : Welcome
09:15 : Opening talk
11:00 : Planning for breakout groups
12:00 : Lunch
12:30 : Breakout groups 
16:00 : Debriefing
16:50 : Closing

**Comment by vmbrasseur** [comment]
Suggestions from the call

* Rephrase the "opening talk" to something like "team show & tell"
* Similarly casual-ize the "debriefing"

**Comment by awz** [comment]
How should we communicate expectations around 5min talks to each team and data stewards?

**Comment by vmbrasseur** [comment]
I believe @raynamharris is composing an email for that. Rayna, please correct me if email composing was on my plate instead.

**Comment by raynamharris** [comment]
@vmbrasseur I've been dragging my feet with this one, but here is some text to start and two questions.

We would like to kick off the May workshop by having a representative from each team and the data steward give a 5 min "show and tell" talk. The goal of these talks is for everyone in the Data Commons to gain a better sense of who's who, what people are working on, and what you hope to get out of the workshop. Slides are not required, but if you prepare sides, please upload them to the Google Drive (link here). 

Do I need to explicitly state that the talk can be given by anyone, not just team leaders or managers? 
Do I need to explicitly state that it is somewhat informal and that is no prescripted format?

**Comment by vmbrasseur** [comment]
@raynamharris 

1. I think it would be helpful to point out that anyone can give the talk, yeah. I think that will encourage participation by more of the attendees and help to reinforce…
1. …this. Yeah, we should definitely let folks know that this is informal and their only constraint is that 5 minute thing. This should hopefully help folks loosen up and feel more comfortable sharing, if they know they're not officially being judged or held to some vague standard. :-)

**Comment by raynamharris** [comment]
Okay, I modified my paragraph to include @vmbrasseur excellent comments. Then, I went ahead and two short paragraphs encouraging people to view the issues and to (optionally) play Avi's little network game or look at my cheat sheet. See #40 

Let me know if you think its good to go. Feel free to push edits.

**Comment by vmbrasseur** [comment]
These are great! Thank you!
