### ISSUE TITLE
Registration temporarily closed - suggestions for balancing attendance 

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#92]
Morning email to workshop registrants: 

> Registration is temporarily closed. You can view the current [list of attendees here](http://nih-data-commons.us/2018-september-workshop/attendees). I have space for 10 more people, but I imagine many more than 10 want to attend, so we must prioritize and perhaps adjust. Teams Calcium, Helium, Hydrogen, and Xenon all have 6+ attendees, so I'm capping your team's registration. Please discuss within your team why each person needs to attend as see if it is possible to cut back. Teams Carbon, Nitrogen, Oxygen, Phosphorus, & Sodium only have 1 attendee, but I imagine would like to send more. Action item: please contact Rayna Harris (via slack or email) with the names of attendees you would like to remove or add by Tues. Sept 4th.

If you have suggestions for how to redistribute the current attendee list to accommodate interest but maintain a balanced distribution, please send them here.

**Comment by raynamharris** [comment]
From Carl

> Put a cap on this.  N slots per team. Then the week before, if there are still slots release them.

**Comment by charlesreid1** [comment]
I like this approach - diplomatic, numbers-based, takes human decisions about who to allow out of the loop.

**Comment by raynamharris** [comment]
Update: Registration was opened and people registered by the dozens. It is now closed again. Final agenda is http://nih-data-commons.us/2018-september-workshop/attendees

**Comment by nlharris** [comment]
There are some duplicates in the attendee list, e.g.,
> ## 29         Copper         Rudy Potenzone
> ## 30         Copper         Rudy Potenzone
> ## 31         Copper               S. Edrie
> ## 32         Copper     Sarah Wait Zaranek
> ## 33         Copper     Sasha Wait Zaranek

**Comment by raynamharris** [comment]
Thanks! That "sarah" and "sasha" similarity fools people every time.

**Comment by raynamharris** [comment]
I feel like a hard limit on attendee per team will be difficult because of unbalanced team size. I do like a cap on a given members attendee (say 2 meetings per year). Here so data viz on workshop participation (actual files are in PR https://github.com/dcppc/dcppc-workshops/pull/97).

![attendance-1](https://user-images.githubusercontent.com/7544197/45394908-d7182200-b5f8-11e8-9c7f-61b8be26224e.png)
![attendance-2](https://user-images.githubusercontent.com/7544197/45394909-d7182200-b5f8-11e8-9643-e8dd442437ba.png)

**Comment by nlharris** [comment]
> Thanks! That "sarah" and "sasha" similarity fools people every time.

OMG, you're right. However, there were two instances of Rudy.

**Comment by raynamharris** [comment]
Registration closed again. Total attendance is near 100. Updated email sent to attendees https://github.com/dcppc/dcppc-workshops/pull/103
