### ISSUE TITLE
collecting a list of people on the waitlist 

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#93]
- a few from Avi's group
- Ravi Madduri, Mike DArcy, Carl, Rick, Rob Schuler  - argon
- Bob, Michelle, Kemi and Jonathan - phosphorus
- Ken Rice and Ben Heavner TOPMed DCC representatives 
- Jennifer Smith, Mary, Adam Wright AGR
- Claris, Ray, Kira, and Anne Thessen- Helium
- Francois Aguet - GTex
- Jeff De Pons and Mary Shimoyama - AGR
- Merce Crosas, Tim Clark, Manuel Bernal Llinares, Max Levinson - sodium
- Greg Versmee and Laura Versmee (carbon)
- David Steinberg
- Remove Helena, add Marina Elsiver

**Comment by vindie13** [comment]
Most of these people are now on the list. Is this Issue done?

**Comment by raynamharris** [comment]
Yes! All are added
